// <auto-generated />
using System;
using IDM.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IDM.Migrations
{
    [DbContext(typeof(SpuContext))]
    [Migration("20201112134332_AlterGroupUser2")]
    partial class AlterGroupUser2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IDM.Models.AuditLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IDM.Models.Aumphur", b =>
                {
                    b.Property<int>("AumphurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AumphurCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("AumphurName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("AumphurNameEn")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.HasKey("AumphurID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Aumphurs");
                });

            modelBuilder.Entity("IDM.Models.Guest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ADCreated")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ApprovalBy")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("AumphurID")
                        .HasColumnType("int");

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("GuestCode")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("IDCard")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("MacAddress1")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<string>("MacAddress2")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<string>("MacAddress3")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<bool>("OTPVerify")
                        .HasColumnType("bit");

                    b.Property<int?>("OUID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<int>("RegisterType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TumbonID")
                        .HasColumnType("int");

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AumphurID");

                    b.HasIndex("OUID");

                    b.HasIndex("ProvinceID");

                    b.HasIndex("TumbonID");

                    b.HasIndex("UserID");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("IDM.Models.GuestImport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ApprovalBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("AumphurID")
                        .HasColumnType("int");

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("GuestCode")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("IDCard")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int>("ImportLine")
                        .HasColumnType("int");

                    b.Property<string>("ImportRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImportVerify")
                        .HasColumnType("bit");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("MacAddress1")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<string>("MacAddress2")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<string>("MacAddress3")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<int?>("OUID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<int>("RegisterType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TumbonID")
                        .HasColumnType("int");

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AumphurID");

                    b.HasIndex("OUID");

                    b.HasIndex("ProvinceID");

                    b.HasIndex("TumbonID");

                    b.ToTable("GuestImports");
                });

            modelBuilder.Entity("IDM.Models.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("int");

                    b.Property<string>("LanguageKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("LanguageValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("IDM.Models.OTP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("Expire_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("OTPNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("RefNo")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("SendMessageType")
                        .HasColumnType("int");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("IDM.Models.OU", b =>
                {
                    b.Property<int>("OUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Editable")
                        .HasColumnType("bit");

                    b.Property<string>("OUDescription")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("OUName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.HasKey("OUID");

                    b.ToTable("OUs");
                });

            modelBuilder.Entity("IDM.Models.Province", b =>
                {
                    b.Property<int>("ProvinceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ProvinceNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceID");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("IDM.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int?>("OUID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("OUID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IDM.Models.Setup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Base")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LDAPBase")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LDAPHost")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LDAPPassword")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LDAPPort")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LDAPUsername")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("SMTP_From")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("SMTP_Password")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("SMTP_Port")
                        .HasColumnType("int");

                    b.Property<bool?>("SMTP_SSL")
                        .HasColumnType("bit");

                    b.Property<string>("SMTP_Server")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("SMTP_Username")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID");

                    b.ToTable("Setups");
                });

            modelBuilder.Entity("IDM.Models.Tumbon", b =>
                {
                    b.Property<int>("TumbonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AumphurCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("AumphurID")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("TumbonCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("TumbonName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("TumbonNameEn")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("TumbonID");

                    b.HasIndex("AumphurID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Tumbons");
                });

            modelBuilder.Entity("IDM.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IDM.Models.faculty", b =>
                {
                    b.Property<int>("faculty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by_username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("faculty_distinguish_name_affiliate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faculty_distinguish_name_outsider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faculty_distinguish_name_staff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faculty_distinguish_name_student")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faculty_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faculty_name_eng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faculty_shot_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("faculty_telephonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modified_by_username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("faculty_id");

                    b.ToTable("table_cu_faculty");
                });

            modelBuilder.Entity("IDM.Models.faculty_level2", b =>
                {
                    b.Property<int>("sub_office_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("create_by_username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("faculty_id")
                        .HasColumnType("int");

                    b.Property<string>("faculty_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_office_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_office_name_eng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_office_shot_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_office_telephonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sub_office_id");

                    b.ToTable("table_cu_faculty_level2");
                });

            modelBuilder.Entity("IDM.Models.group", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("group_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_manage_distinguish_name_list")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("group_priority")
                        .HasColumnType("int");

                    b.Property<string>("group_username_list")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("group_id");

                    b.ToTable("table_group");
                });

            modelBuilder.Entity("IDM.Models.group_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("group_id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("user_id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("group_id");

                    b.HasIndex("user_id");

                    b.ToTable("table_group_user");
                });

            modelBuilder.Entity("IDM.Models.visual_fim_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Create_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Create_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("Update_By")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("Update_On")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("basic_cn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_dn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_givenname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_sn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_telephonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_uid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("basic_userprincipalname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_CUexpire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_gecos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_jobcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_mailRoutingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_mailacceptinggeneralid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_maildrop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_mailhost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_nsaccountlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_pplid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_pwdchangedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_pwdchangedloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_sce_package")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_thcn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cu_thsn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("internetaccess")
                        .HasColumnType("int");

                    b.Property<string>("mail_miWmprefCharset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail_miWmprefEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail_miWmprefFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail_miWmprefReplyOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail_miWmprefTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("netcastaccess")
                        .HasColumnType("int");

                    b.Property<string>("system_answer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_answer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_answer3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_create_by_uid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("system_create_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("system_enable_password_forgot")
                        .HasColumnType("int");

                    b.Property<int?>("system_faculty_id")
                        .HasColumnType("int");

                    b.Property<string>("system_last_accessed_by_uid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("system_last_accessed_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("system_modify_by_uid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("system_modify_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("system_org")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_question1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_question2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_question3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("system_sub_office_id")
                        .HasColumnType("int");

                    b.Property<int?>("system_temporary_user_expire_date_counter")
                        .HasColumnType("int");

                    b.Property<int?>("system_waiting_time_for_access")
                        .HasColumnType("int");

                    b.Property<string>("unix_gidNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unix_homeDirectory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unix_inetCOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unix_loginShell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unix_uidNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("UserID");

                    b.ToTable("table_visual_fim_user");
                });

            modelBuilder.Entity("IDM.Models.Aumphur", b =>
                {
                    b.HasOne("IDM.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IDM.Models.Guest", b =>
                {
                    b.HasOne("IDM.Models.Aumphur", "Aumphur")
                        .WithMany()
                        .HasForeignKey("AumphurID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.OU", "OU")
                        .WithMany()
                        .HasForeignKey("OUID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.Tumbon", "Tumbon")
                        .WithMany()
                        .HasForeignKey("TumbonID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IDM.Models.GuestImport", b =>
                {
                    b.HasOne("IDM.Models.Aumphur", "Aumphur")
                        .WithMany()
                        .HasForeignKey("AumphurID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.OU", "OU")
                        .WithMany()
                        .HasForeignKey("OUID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.Tumbon", "Tumbon")
                        .WithMany()
                        .HasForeignKey("TumbonID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IDM.Models.Role", b =>
                {
                    b.HasOne("IDM.Models.OU", "OU")
                        .WithMany()
                        .HasForeignKey("OUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IDM.Models.Tumbon", b =>
                {
                    b.HasOne("IDM.Models.Aumphur", "Aumphur")
                        .WithMany()
                        .HasForeignKey("AumphurID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IDM.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IDM.Models.group_user", b =>
                {
                    b.HasOne("IDM.Models.group", "group")
                        .WithMany()
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IDM.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IDM.Models.visual_fim_user", b =>
                {
                    b.HasOne("IDM.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
